/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface Chat$Params {
  
    /**
     * AI chat request
     */
    body: {
'message': string;
'context'?: {
};
'session_id'?: number;
}
}

export function chat(http: HttpClient, rootUrl: string, params: Chat$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'content'?: string;
'session_id'?: number;
'usage'?: {
'input_tokens'?: number;
'output_tokens'?: number;
'total_tokens'?: number;
};
}>> {
  const rb = new RequestBuilder(rootUrl, chat.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'content'?: string;
      'session_id'?: number;
      'usage'?: {
      'input_tokens'?: number;
      'output_tokens'?: number;
      'total_tokens'?: number;
      };
      }>;
    })
  );
}

chat.PATH = '/ai/chat';
