/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: AuditLogWithRelations, schemaOptions: { includeRelations: true })
 */
export interface AuditLogWithRelations {
  action: string;
  created_at?: string;
  error_message?: string;
  ip_address?: string;
  log_id?: number;
  new_value?: string;
  old_value?: string;
  operator_id: string;
  operator_name?: string;
  request_method: string;
  request_path: string;
  resource_id?: string;
  resource_type: string;
  status_code?: number;
}
