/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Partial<Department>, schemaOptions: { partial: true })
 */
export interface DepartmentPartial {
  dept_code?: string;
  dept_desc?: string;
  dept_desc_a?: string;
  dept_id?: number;
}
