/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: DepartmentWithRelations, schemaOptions: { includeRelations: true })
 */
export interface DepartmentWithRelations {
  dept_code?: string;
  dept_desc?: string;
  dept_desc_a?: string;
  dept_id: number;
}
