/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: EmployeeWithRelations, schemaOptions: { includeRelations: true })
 */
export interface EmployeeWithRelations {
  Sex?: boolean;
  dept_desc?: string;
  employee_id: string;
  hasaccess?: boolean;
  hire_date?: string;
  name?: string;
  name_a?: string;
  password?: string;
  plant_name?: string;
  region_name?: string;
  resin_date?: string;
  role_id?: number;
  status?: boolean;
}
