/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Plant, schemaOptions: { title: 'NewPlant' })
 */
export interface NewPlant {
  plant_id?: number;
  plant_name?: string;
  site?: string;
}
