/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Region, schemaOptions: { title: 'NewRegion' })
 */
export interface NewRegion {
  latitude?: number;
  longitude?: number;
  region_id?: number;
  region_name?: string;
  region_name_cn?: string;
}
