/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Department, schemaOptions: { title: 'NewDepartment' })
 */
export interface NewDepartment {
  dept_code?: string;
  dept_desc?: string;
  dept_desc_a?: string;
  dept_id: number;
}
