/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Partial<Plant>, schemaOptions: { partial: true })
 */
export interface PlantPartial {
  plant_id?: number;
  plant_name?: string;
  site?: string;
}
