/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: PlantWithRelations, schemaOptions: { includeRelations: true })
 */
export interface PlantWithRelations {
  plant_id?: number;
  plant_name?: string;
  site?: string;
}
