/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Region {
  latitude?: number;
  longitude?: number;
  region_id?: number;
  region_name?: string;
  region_name_cn?: string;
}
