/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Partial<Region>, schemaOptions: { partial: true })
 */
export interface RegionPartial {
  latitude?: number;
  longitude?: number;
  region_id?: number;
  region_name?: string;
  region_name_cn?: string;
}
