/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: RegionWithRelations, schemaOptions: { includeRelations: true })
 */
export interface RegionWithRelations {
  latitude?: number;
  longitude?: number;
  region_id?: number;
  region_name?: string;
  region_name_cn?: string;
}
