/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Role {
  auth_page_auth?: number;
  description?: string;
  home_page_auth?: number;
  is_super_admin?: boolean;
  log_page_auth?: number;
  report_page_auth?: number;
  role_id?: number;
  role_name?: string;
}
