/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: RoleWithRelations, schemaOptions: { includeRelations: true })
 */
export interface RoleWithRelations {
  auth_page_auth?: number;
  description?: string;
  home_page_auth?: number;
  is_super_admin?: boolean;
  log_page_auth?: number;
  report_page_auth?: number;
  role_id?: number;
  role_name?: string;
}
