/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuditLogWithRelations } from './models/audit-log-with-relations';
export type { Department } from './models/department';
export type { DepartmentPartial } from './models/department-partial';
export type { DepartmentWithRelations } from './models/department-with-relations';
export type { Employee } from './models/employee';
export type { EmployeePartial } from './models/employee-partial';
export type { EmployeeWithRelations } from './models/employee-with-relations';
export type { Count as LoopbackCount } from './models/loopback/count';
export type { NewDepartment } from './models/new-department';
export type { NewEmployee } from './models/new-employee';
export type { NewPlant } from './models/new-plant';
export type { NewRegion } from './models/new-region';
export type { NewRole } from './models/new-role';
export type { PingResponse } from './models/ping-response';
export type { Plant } from './models/plant';
export type { PlantPartial } from './models/plant-partial';
export type { PlantWithRelations } from './models/plant-with-relations';
export type { Region } from './models/region';
export type { RegionPartial } from './models/region-partial';
export type { RegionWithRelations } from './models/region-with-relations';
export type { Role } from './models/role';
export type { RolePartial } from './models/role-partial';
export type { RoleWithRelations } from './models/role-with-relations';
