
INSERT INTO  users   ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10609028', '陳志強', 'ALEX CC CHEN', 'WHC', NULL, '23M100', '機構設計中心I', 'Mech. Design Center I');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10609097', '康志豪', 'ALLEN KANG', 'WHC', NULL, '2S0230', '軟體研發三部', 'S/W R&D Dept. III');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10609125', '陳少興', 'SHAOSHIN CHEN', 'WEKS', 'Plant 3', '5ML500', '製程工程二部', 'Process Eng.Department II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10610026', '陳致豪', 'PETER CHEN', 'WHC', NULL, '2S0220', '軟體研發二部', 'S/W R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10610066', '陳皓哲', 'CHARLIE HJ CHEN', 'WHC', NULL, '2Q0210', '系統測試部', 'System Testing');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10611011', '江柏儀', 'BOB CHIANG', 'WHC', NULL, '270R10', '硬體研發一部', 'H/W R&D Dept. I');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10611712', '葉振揚', 'KEVIN YEH', 'WHC', 'Plant 3', '50DG00', '無線系統測試驗證部', 'RF System Test &Validation Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10612049', '吳亞唐', 'AJAY WU', 'WEKS', 'Plant 3', '5ML620', '試產二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10703049', '陳紹平', 'ALLEN SP CHEN', 'WHC', NULL, '250M00', '機構設計', 'Mechanical Design');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10703050', '徐正熙', 'HILL HSU', 'WHC', NULL, '250M00', '機構設計', 'Mechanical Design');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10703121', '紀明宗', 'GAVIN CHI', 'WEKS', 'Plant 3', '5M5600', '製造六部', 'Manufacturing Dept. VI');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10703810', '劉家甫', 'WEBBER LIU', 'WHC', NULL, '23D100', '電子研發部', 'Electronic R&D Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10704118', '陳懷英', 'JIMMY CHEN', 'WEKS', 'Plant 3', '5ML700', '製程專案部', 'Process Project Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10704710', '郭泓邑', 'AUSTIN KUO', 'WHC', 'Plant 3', '50D600', '系統開發設計部', 'System Dev.Design Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10705131', '黃麟翔', 'FRANK LX HUANG', 'WEKS', 'Plant 3', '5M5300', '製造三部', 'Manufacturing Dept. III');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10707057', '蔡洛緯', 'LUCAS TSAI', 'WHC', NULL, '20RM00', '產品一部', 'Product Dept. I');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10710092', '陳則銘', 'CHRIS ZM CHEN', 'WHC', NULL, '230P50', '產品協調部', 'PCC Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10711045', 'Berlin', 'Berlin Lin', 'WHQ', NULL, 'NR0200', '方案2', NULL);
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10801007', '謝育琦', 'CHAD YC HSIEH', 'WHC', NULL, 'DVCS00', '軟體研發部', 'S/W R&D Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10802052', '翁祥峻', 'AARON WENG', 'WHC', NULL, 'DV0P00', '產品經理中心', 'Product Mgmt. Center');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10802115', '林祐緯', 'WESLEY LIN', 'WKS', 'Site Unit', 'DMA610', '軟體技術開發課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10803703', '周心平', 'CINDY CHOU', 'WEKS', 'Plant 3', '50DD00', '無線系統管理部', 'RF System Mgmt. Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10804131', '王世福', 'TOM SF WANG', 'WEKS', 'Plant 3', '50C000', '工業工程處', 'Industrial Engineering Div.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10807059', '王哲凱', 'BRUCE CK WANG', 'WEKS', NULL, '50J000', '支援專案室', 'Support & Project Office');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10807101', '許振良', 'JACKY CL HSU', 'WEKS', 'Plant 3', '5M3000', 'FATP A3廠', 'FATP Plant A3');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10809014', '陳怡君', 'VICKEY CHEN', 'WHC', NULL, '230R60', '品質與客戶滿意六部', 'Quality and Customer Satisfact Dept.VI');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10809072', '張笙又', 'JOSEPH SY CHANG', 'WHC', NULL, '20RS00', '業務暨產品發展部', 'Account & Product Development Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10811108', '陳榮峰', 'DILLON CHEN', 'WIH', NULL, 'DSE200', '光電品質管理部', 'Optronics Quality Mgmt. Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10812039', '郭國慶', 'TERRANCE KUO', 'WKS', NULL, '2Q03R0', '昆山測試三部', 'WKS Testing Dept. III');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10812240', '游郅綱', 'GARY CK YU', 'WKS', 'Site Unit', 'DMS620', '資料分析二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10901015', '林鼎鈞', 'TINGCHUN LIN', 'WHC', NULL, '2Q0210', '系統測試部', 'System Testing');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10901901', '劉加恩', 'JIAEN LIU', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10901902', '呂惠雯', 'SANDY HW LU', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10901909', '蔡明菁', 'MAGGIE MC TSAI', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902027', '張志翰', 'CHIHHAN CHANG', 'WHC', NULL, '20RP00', '產品二', 'Product II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902070', '王柏文', 'BENNY BW WANG', 'WHC', NULL, '23D100', '電子研發部', 'Electronic R&D Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902113', '林宗鵬', 'BILL TP LIN', 'WMY', NULL, 'KM1600', 'PCBA 生產部', 'PCBA Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902133', '魏仙翠', 'RIVA WEI', 'WIH', NULL, 'DSE100', '電子品質管理部', 'EE Quality Mgmt. Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902145', '湯立婷', 'LITING TANG', 'WIH', 'Site Unit', 'DMS620', '資料分析二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902802', '陳湘婷', 'KIMMY CHEN', 'WHC', NULL, '230S30', '業務行銷二部', 'AM Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902803', '黃昱翔', 'AUSTIN HUANG', 'WHC', NULL, '270T00', '自動化研發', 'Automation R&D');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902911', '林志勇', 'KEN ZY LIN', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902918', '陽亞汝', 'YAJU_YANG', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902929', '莊明璋', 'ZHUANGMING ZHAN', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902935', '陳素徽', 'SUSAN SH CHEN', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902936', '陳立浩', 'LIHAO CHEN', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10902938', '豐自吉', 'AFI TJ FENG', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10903010', '鄭富耘', 'JOHN FY CHENG', 'WHC', NULL, '23D000', '硬體研發處', 'H/W R&D Division');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10903905', '林隴成', 'LUNGCHENG LIN', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10903909', '許恩賜', 'ENTZU HSU', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10903911', '林芬芳', 'FENFANG LIN', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10904076', '石美琪', 'MEGAN SHIH', 'WHC', NULL, '20RM00', '產品一部', 'Product Dept. I');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10905003', '盧宥全', 'IVAN LU', 'WEKS', NULL, '50J000', '支援專案室', 'Support & Project Office');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10906036', '陳雅玲', 'PATRICK PC LINR', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10906042', '裘娃·伊斯巴里達夫', 'ALFIE HUANGRE', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10906043', '喇尼忽·伊斯巴里達夫', 'HUGO LEERE', 'WHC', NULL, '20R200', '研發二部', 'R&D Dept. II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10906070', '高柏昇', 'BOSON KAO', 'WEKS', NULL, '50J000', '支援專案室', 'Support & Project Office');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10906084', '詹凱峰', 'JAMES ADAMS', 'WHC', NULL, '20RS00', '業務暨產品發展部', 'Account & Product Development Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10907002', '劉千聖', 'MARTIN LIU', 'WEKS', 'Plant 3', '5M1800', '製造八部', 'Manufacturing Dept. VIII');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10907046', '徐榮臨', 'LONELY HSU', 'WEKS', 'Plant 3', '5MA500', '環安系統部', 'Environment Safety System Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10907230', '許雅婷', 'IRIS YT HSU', 'WKS', 'Entrusted ', 'TEST01', NULL, NULL);
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10908001', '范証東', 'JERRY CT FAN', 'WEKS', 'Plant 3', '5M5300', '製造三部', 'Manufacturing Dept. III');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10908073', '蔡承軒', 'REG TSAI', 'WHC', NULL, 'DSS000', '策略專案室', 'Strategic Project Office');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10908078', '陳政維', 'CHENGWEI CHEN', 'WHC', NULL, '230I30', '機器人智慧導航部', 'Robot AI Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('10908803', '馮炳雄', 'VINCE FENG', 'WHC', NULL, '50J000', '支援專案室', 'Support & Project Office');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('200911459', '楊程', 'ELAINE YANG', 'WZS', 'Plant 8', 'MZ8B71', 'F01-D組', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('7710028', '田燿圻', 'RICKY TAIN', 'WMY', NULL, 'KM1000', '馬來西亞廠', 'Malaysia Plant');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('7806609', '廖建忠', 'ROGER LIAO', 'WEKS', NULL, '5MS000', '材料品質處', 'Material Quality Division');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('8408159', '張聰耀', 'BENJAMIN CHANG', 'WKS', 'Entrusted ', 'DM0000', '全球製造', 'Operations');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('8606274', '吳武銓', 'JASON WU', 'WEKS', 'Plant 3', '5ML000', 'MLB廠', 'MLB Plant');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('8902047', '賴玫玲', 'MAY LAI', 'WHC', NULL, '2S0S00', '軟體支援中心', 'S/W Supporting Center');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('9111016', '洪啟敏', 'TODD HUNG', 'WEKS', NULL, '5MS100', '機構件供應商品質管理部', 'ME SQM Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('9209102', '汪彥暉', 'WEASLY UANG', 'WEKS', 'Plant 3', '50D500', 'WGT測試部', 'WGT Testing Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('9306171', '黃逸軒', 'JIMMY HUANG', 'WEKS', 'Plant 3', '5ML200', '半成品生產二部', 'MLB Production Department II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('9410033', '何鳳玲', 'LILIAN HO', 'WHC', NULL, '230S00', '業務行銷中心', 'Account Management Center');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('9412003', '蔡東陵', 'TONY DL TSAI', 'WHC', NULL, '500000', '智能裝置事業群', 'Smart Devices Business Group');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('9601107', '張傳忠', 'DAVID CC CHANG', 'WEKS', 'Plant 3', '5MA000', '行政處', 'Adm. Division');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('9807066', '張黎文', 'LILIAN CHANG', 'WHC', NULL, '2K0F00', '業務管理部', 'Fulfillment Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('9908056', '藍常楓', 'FENG LAN', 'WHC', NULL, '23M200', '機構設計中心II', 'Mech. Design Center II');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('chaunceyyuan', '袁成新', 'Chauncey Yuan', 'WKS', 'TEST', 'TEST01', NULL, NULL);
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('CS15', 'SAROJAMMA', 'SAROJAMMA', 'WMI', NULL, 'KN0A10', 'WMI HR Department', 'HR Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('dams_admin', '系統管理員', 'Administrator', 'WKS', NULL, '', '', '');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS121109', 'MALLESH  K', 'MALLESH K', 'WMI', NULL, 'KN0A10', 'WMI HR Department', 'HR Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS130108', 'SHIVA KUMAR  L', 'SHIVAKUMAR L', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS151204', 'LAKSHMIKANTH  K', 'LAKSHMIKANTH K ', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS160256', 'NISHANTH  D N', 'NISHANTH', 'WMI', NULL, 'KN0I00', 'IT Department', 'IT Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS160309', 'YATHISH M S', 'YATHISH M S', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS170219', 'LOKESH  K R', 'LOKESH KR', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS170404', 'BHAVYASHRI  K K', 'BHAVYASHRI KK', 'WMI', NULL, 'KN0A10', 'WMI HR Department', 'HR Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS170412', 'SANTOSH GANESH ', 'SANTOSH AMBIG', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS170624', 'DHARAKUMAR  B', 'DHARA KUMAR B', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS171003', 'RAKESH  DD', 'RAKESH D D', 'WMI', NULL, 'KN0I00', 'IT Department', 'IT Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS171004', 'SATHISHKUMAR  S', 'SATHISH KUMAR S', 'WMI', NULL, 'KN0A10', 'WMI HR Department', 'HR Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS171116', 'HARISH  M P', 'HARISH MP', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS171136', 'SHABIR SAB', 'SHABIR SAB', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS171141', 'PARTHASARATHI  ', 'PARTHASARATHI', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS171206', 'AMARANATHA  D', 'AMARANATHA  D', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS180101', 'BHOOPALA  M', 'BHOOPALA M', 'WMI', NULL, 'KN0A10', 'WMI HR Department', 'HR Dept.');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS180606', 'GANESHA  HADED', 'GANESH HH', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS181015', 'LOHITH  C', 'LOHITH C', 'WMI', NULL, 'KN0S00', 'Sourcing Department', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('ISMS200901', 'MAITHRI N', 'MAITHRI N', 'WMI', NULL, 'KN0S00', 'Sourcing Departmen', 'Sourcing Department');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J14020837', '李樹琴', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J15030992', '薛曉梅', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J17020149', '李偉', ' ', 'WTZ', 'Site Unit', 'KP0U80', '廠務二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J17050205', '馬雪飛', 'LUCKY XF MA', 'WTZ', 'Entrusted ', '310110', '業務管理課', 'Fulfillment Section');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J17060143', '范庭祥', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J17070243', '張夢娟', 'MENGJUAN ZHANG', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J17090128', '潘嘉兵', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J17102283', '曹晨', 'CHEN CZ CAO', 'WTZ', 'LCM', 'KP2G20', '生產工程課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J17110055', '淩建忠', ' ', 'WTZ', 'LCM', 'KP2V10', '倉儲管理一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18030641', '潘偉麗', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18030923', '馮鳳杰', ' ', 'WTZ', 'LCM', 'KP2Q10', '供應商管理課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18031083', '孔繁東', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18050097', '段飛梅', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18050921', '陶龍', 'LONGLONG TAO', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18060033', '封倩', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18070170', '蘇春艷', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18070277', '於瓊', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18090022', '崔利芳', 'LIFANG CUI', 'WTZ', 'LCM', 'KP2Q30', '品質系統課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18100043', '陳芬', ' ', 'WTZ', 'Site Unit', 'KPHT20', '行政課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J18120005', '潘虹', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19020076', '段雪茹', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19060118', '徐正新', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19060165', '黃丹雯', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19060341', '蘇宇', ' ', 'WTZ', 'Site Unit', 'KP0U70', '廠務一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19060431', '段欣欣', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19070074', '霍凡', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19070156', '汪黎明', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19080032', '王青', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19080697', '懷點點', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19080708', '劉細香', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19083890', '毛蒙蒙', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19090019', '杜菊燕', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19090117', '李銘文', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19093350', '曹雲華', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19100082', '薛為寶', ' ', 'WTZ', 'LCM', 'KP2Q10', '供應商管理課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19100096', '金榮', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19110131', '姚強', ' ', 'WTZ', 'Site Unit', 'KPHT20', '行政課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19110230', '趙杏', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19110662', '高煌', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19110663', '郭？騰', ' ', 'WTZ', 'LCM', 'KP2G20', '生產工程課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19120053', '徐建書', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J19120153', '唐潔', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20020071', '閆章磊', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20020078', '李成', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20020089', '張文超', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20020092', '王世浩', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20020131', '杜麗娟', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20020156', '馬翔', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20020184', '翁國華', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20020200', '白增', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20020205', '曹靜', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20020257', '彭燁斌', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030005', '曹國軍', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030024', '朱沛', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030037', '陸明生', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030107', '李紅崗', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030188', '周志堅', ' ', 'WTZ', 'Site Unit', 'KPHT20', '行政課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030205', '申彬彬', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030206', '郭俊杰', ' ', 'WTZ', 'LCM', 'KP2V10', '倉儲管理一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030210', '舒治賢', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030226', '王順', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030256', '張凱', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030314', '楊輝', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030337', '項雲濤', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030355', '楊小克', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030357', '吳曉宇', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030369', '鮑秀鵬', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030372', '曹進', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030409', '李明嫻', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030410', '陳源源', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030446', '袁靖雯', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030459', '沈迎雙', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030477', '李嘉欣', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030508', '任萌萌', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030517', '左翔', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030521', '詹濤', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030522', '劉祥義', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030542', '王辛萌', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030561', '雷永', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030585', '竇文健', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030590', '張子毅', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030592', '張秀萍', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030642', '范婷婷', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030658', '孫發濤', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030659', '田翠', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030662', '田興旺', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030663', '李立豐', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030667', '周仁福', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030670', '王寧飛', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030679', '廖雙敏', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030688', '代靜怡', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030791', '聶洵', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030864', '張新明', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030875', '馬賀', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030940', '時濤', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030945', '赫鑫磊', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030959', '馬軒雨', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20030994', '孫永祥', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031024', '趙耀', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031026', '許玩玩', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031028', '王自榮', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031033', '崔麗麗', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031034', '王聰', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031037', '袁延鵬', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031041', '余志洋', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031059', '孔令坤', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031061', '姚洋洋', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031073', '劉江', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031081', '冀山山', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031110', '陳茂紅', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031114', '李可心', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031134', '張海誓', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031149', '王雪', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031157', '王朋舉', ' ', 'WTZ', 'LCM', 'KP2R30', 'DL訓練課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031170', '王常？', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031171', '晁岱軒', ' ', 'WTZ', 'LCM', 'KP2G20', '生產工程課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031172', '趙飛飛', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031178', '楊錄廣', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031179', '劉愛麗', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031253', '王野帆', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20031260', '邱冬', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040003', '馮石磊', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040040', '孔富華', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040041', '徐長董', ' ', 'WTZ', 'LCM', 'KP2G20', '生產工程課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040069', '董瑤', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040077', '王國良', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040086', '王昌', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040087', '苑自力', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040088', '劉旭', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040102', '段志鑫', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040110', '劉金虎', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040119', '李方均', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040125', '李榮杰', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040126', '宋斌', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040141', '伊志會', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040142', '胡超博', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040159', '閆俊芳', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040166', '王久觀', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040174', '高金超', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040176', '尹園園', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040177', '尹雙鳳', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040187', '王凱', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040210', '王宇星', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040225', '李志杰', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040233', '周曹鑫', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040236', '閆向陽', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040240', '李志逢', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040249', '王立朋', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040251', '張德利', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040282', '羅東', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040286', '高偉', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040313', '鐘源源', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040315', '孫佳成', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040324', '張麗', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040350', '李響', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040357', '刁路程', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040366', '李玉芳', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040400', '曾淑雅', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040416', '魏文蘭', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040417', '郭建康', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040422', '劉健', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040430', '崔曉棟', ' ', 'WTZ', 'LCM', 'KP2V20', '倉儲管理二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040447', '雷顯蓉', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040458', '馮萬元', ' ', 'WTZ', 'LCM', 'KP2G20', '生產工程課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040466', '尚小哲', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040478', '陳明瓊', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040490', '孔泳迪', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040502', '陳言香', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040519', '於桂霖', ' ', 'WTZ', 'LCM', 'KP2Q30', '品質系統課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040546', '周杰', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040554', '蔣蘇香', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040565', '劉正', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040609', '原帥', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040621', '劉威', 'WEI LL LIU', 'WTZ', 'LCM', 'KP2G20', '生產工程課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040628', '伏小偉', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040670', '楊瑞炫', ' ', 'WTZ', 'LCM', 'KP2G20', '生產工程課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040728', '李好丹', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040809', '胡偉民', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040836', '季成飛', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040842', '申現闖', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040853', '夏楠楠', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040903', '曲麗濤', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040909', '白明芝', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040947', '劉長輝', ' ', 'WTZ', 'LCM', 'KP2V10', '倉儲管理一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040950', '孫振', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20040968', '白璐', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005001A', '王耀悅', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005002A', '高欽格', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005003A', '張亞藍', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050046', '王成業', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005004A', '高怡', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005006A', '李浩天', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005007X', '蘇朝銀', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050088', '田玉寶', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005008A', '劉依銳', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005009A', '賈瑞雪', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005009X', '田勇', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005010A', '劉媛媛', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005010X', '周琪', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050112', '周文娟', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005011A', '楚芬芳', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005011X', '段前勇', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005012X', '國奇', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050137', '李付英', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005013A', '齊唐晶', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005013X', '彭勝', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005014A', '羅佳美', ' ', 'WTZ', 'LCM', 'KP2R30', 'DL訓練課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005016X', '鄭錫亮', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005017A', '張源', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005017X', '吳驚', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005018X', '彭填', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050204', '劉瑞峰', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005021A', '張慶慶', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050233', '張文濤', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050236', '陳懷東', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005023A', '王佳慧', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005024A', '杜麗娟', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005026A', '張？杰', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050278', '李東海', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005027A', '王馨雨', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050289', '李濤', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050309', '張蒙恩', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005030A', '王佳', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050312', '王健', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005031A', '董夢如', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050323', '黃濤', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005032A', '李夢華', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005033A', '王欣', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005034A', '種晴晴', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005035A', '司雨', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050361', '田鳳延', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050363', '齊永麗', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005036A', '高亞丹', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050376', '馬丹', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050377', '柳楚平', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050396', '郭玉甫', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005040A', '楊碩碩', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005040X', '任永', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050416', '班金龍', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050419', '熊麗', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005041A', '李怡辰', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050421', '錢坤', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050425', '王澤瑞', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005042A', '陳姿伊', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050439', '張先鋒', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005043A', '王怡佳', ' ', 'WTZ', 'LCM', 'KP2R30', 'DL訓練課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005044A', '蔡叢叢', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005045A', '張羽彤', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005046A', '李晶晶', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005046X', '張洪', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050477', '袁燕琴', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050480', '朱亞奇', ' ', 'WTZ', 'LCM', 'KP2G20', '生產工程課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050481', '秦虎國', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050482', '楊天俊', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050483', '楊冬雪', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005048X', '龔政', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050491', '潘實現', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005049X', '胡利軍', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005050X', '曹乙', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005051X', '陳帝', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050528', '姚志豪', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050532', '王善強', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050559', '仉奕程', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005057A', '趙放放', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005058A', '袁星磊', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005059A', '樊夢坷', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050612', '曲帥帥', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050618', '宋凱鋒', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050622', '楊年', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050627', '費新毅', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050632', '張林', ' ', 'WTZ', 'LCM', 'KP2R20', '支援課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050636', '靳躍賓', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050646', '余志瑞', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005064A', '曹迎夏', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050650', '陳翠蘭', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050653', '馬肖陽', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005065A', '余冰雨', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050664', '李曉亮', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005066A', '張湉', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050676', '李飛洋', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050687', '鄧雪瑩', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005068A', '謝璐瑤', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050699', '徐節康', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005069A', '李錦錦', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050700', '王壯壯', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050719', '張蟬娟', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050722', '張？', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050730', '張帥', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050733', '段紅玲', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050735', '榮艷利', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050739', '田寶玉', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005073A', '唐夢茹', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050748', '宗祥貴', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005074A', '侯嘉蓓', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050756', '劉孝平', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005075A', '李曼佳', ' ', 'WTZ', 'LCM', 'KP2R30', 'DL訓練課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005076A', '余柳穎', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050777', '靳亞賓', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050783', '李衛東', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20050784', '徐敬超', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005078A', '羅夢可', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005080A', '張家興', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005081A', '張曉博', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005087A', '葛家興', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005089A', '高尚', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005090A', '李？陽', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005092A', '楊航程', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005093A', '董文韜', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005098A', '郝時茂', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005099A', '宋金培', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005100A', '聶文博', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005102A', '周俊豪', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005106A', '李明', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005108A', '張一震', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005110A', '李有緣', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005111A', '崔航博', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005113A', '王健', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005114A', '張帥宇', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005115A', '陳少輝', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005119A', '楚洋', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005121A', '鄭順意', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005122A', '宋亞鵬', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005124A', '金天宇', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005126A', '龐佳潤', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005127A', '楊凱', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005130A', '姜博友', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005131A', '郭家旺', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005132A', '胡佳明', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005133A', '霍雨波', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005135A', '李意龍', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005141A', '張建豪', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005142A', '季福海', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005143A', '趙孟力', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005146A', '李東華', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005147A', '王俊以', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005150A', '婁元博', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005151A', '趙泓博', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005153A', '賈宸', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005154A', '張佳鑫', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005157A', '霍雨豪', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005158A', '李嘉星', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005159A', '朱福田', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005163A', '桂志斌', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005164A', '陳永超', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005167A', '王昊', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005168A', '夏思雨', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005170A', '唐峰磊', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005171A', '劉佳豪', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005172A', '張彬坤', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005175A', '曹將浩', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005180A', '黃聰穎', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005181A', '王倩', ' ', 'WTZ', 'LCM', 'KP2R20', '支援課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005182A', '白璐璐', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005183A', '馬恩光', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2005185A', '劉夢欣', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006001B', '龍春香', ' ', 'WTZ', 'LCM', 'KP2R30', 'DL訓練課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006002B', '魯陳', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006002C', '賈金豪', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006003B', '唐丹', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060048', '全鐳', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006004B', '劉佳瑤', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060059', '厲玉剛', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006005B', '劉茜', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006005C', '王坤', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060062', '趙爽', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060068', '周敏', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006006B', '周麗君', ' ', 'WTZ', 'LCM', 'KP2Q20', '品質保證課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006006C', '嶽岑錚', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006007B', '黃山珊', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006008B', '汪芷伊', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006008C', '李宇', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006009B', '李菲', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006009C', '袁義范', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006010B', '陳思宏', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006010C', '謝建舉', ' ', 'WTZ', 'LCM', 'KP2R10', '維修課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060117', '諶洪立', ' ', 'WTZ', 'LCM', 'KP2Q10', '供應商管理課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060126', '盧偉峰', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006012B', '華萍', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060136', '嚴波', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060138', '李志文', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060143', '陳勤輝', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060144', '黃楗松', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060145', '胡海', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060147', '魏中國', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006014B', '丁靜', ' ', 'WTZ', 'LCM', 'KP2U20', '制造二課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060154', '熊學軍', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060157', '尹超', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060159', '胡騰歡', ' ', 'WTZ', 'LCM', 'KP2U10', '制造一課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J2006015B', '郭思靜', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
INSERT INTO  users  ( EMPNO ,  NAME,  NAME_A ,  SITE ,  PLANT ,  DEPTCODE ,  DEPTDESCR ,  DEPTDESCR_A ) VALUES ('J20060161', '吳其霖', ' ', 'WTZ', 'LCM', 'KP2U30', '制造三課', ' ');
